# -*- coding: utf-8 -*-
"""For Else, List Comprehension, Lambda Function, Modules Ders Notu

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hRnIT6TH4Bo98IvwYFgKzCYGTig3dSAl

#For Else
-For else yapısı, bir for döngüsünün işlemini tamamladıktan sonra veya döngüde hiçbir öğe olmadığında çalışacak kod parçacığı sağlar.

-Bu yapı, özellikle belirli bir koşulu sağlayan bir öğenin döngü içinde bulunup bulunmadığını kontrol etmek veya döngünün her öğeyi denedikten sonra belirli bir işlemi yapmasını sağlamak için kullanışlıdır.

-For kendi kendine biterse else çalışıyor, break ile biterse else çalışmıyor.
"""

for i in range(5):
    print(i)
else:
    print("For fonksiyonu bitti")

for i in range(5):
    print(i)
    if i == 3:
        break
else:
    print("For fonksiyonu bitti")

numbers = [1, 2, 3, 4, 5]
target = 6

for num in numbers:
    if num == target:
        print("Hedef bulundu")
        break
else:
    print("Hedef bulunamadı")

"""#List Comprehension

-List compherension, liste oluşturma ve dönüştürme işlemlerini daha sade, okunabilir ve kompakt bir şekilde gerçekleştirmek için kullanılır.

-Oluşan yeni liste önceki listeyi değiştirmez.

**Syntax:**

newlist = \[*expression* **for** *item* **in** *iterable* **if** *condition == True*\]
"""

meyveler = ["Elma", "Muz", "Kiraz", "Kivi", "Çilek"]
yeniListe = []

for meyve in meyveler:
    if "a" in meyve: # a karakteri meyve değişkeninde varsa True döner ve bu değişken listeye eklenir
        yeniListe.append(meyve)

print(yeniListe)

# List comprehension değil.

meyveler = ["Elma", "Muz", "Kiraz", "Kivi", "Çilek"]

# i değişkeni meyeveler listesinde döner. i harfi bulunan eleman listeye eklenir
yeniListe = [i for i in meyveler if "i" in i]
print(yeniListe)

"""##Condition"""

newlist = [x for x in meyveler if x != "Elma"]
newlist

# Condition olmak zorunda değil.
newlist = [x for x in meyveler]
newlist

"""##Iterable
Liste, tuple, set vb. gibi yinelenebilir herhangi bir nesne olabilir.
"""

newlist = [x for x in range(10) if x%2==1]
newlist

"""##Expression"""

newlist = [x for x in meyveler]
newlist

newlist = [x.upper() for x in meyveler]
newlist

newlist = ['Sena' for x in meyveler]
newlist

# Expression içinde koşul yazma
newlist = [x if x != "Muz" else "Çilek" for x in meyveler]
newlist
# Muz değilse kendisini döndür, muz ise muz yerine çilek döndür.

"""#Lambda Function

-Lambda fonksiyonları, özellikle küçük ve basit işlemler için hızlı ve kompakt çözümler sunmak amacıyla kullanılır.

**Syntax:**

lambda *arguments* : *expression*
"""

x = lambda a : a + 5
x(4)

multiply = lambda a, b : a * b
multiply(5,3)

sum = lambda a, b, c : a + b + c
print(x(5, 6, 2))

# Sayının karesini almak için

square = lambda x: x ** 2
square(4)

# Lambda fonksiyonunu başka bir fonksiyonun içinde kullanmak için

def myfunc(n):
  return lambda a : a * n

mydoubler = myfunc(2) # Girdiğin her sayıyı 2 ile çarpan fonksiyon
mytripler = myfunc(3) # Girdiğin her sayıyı 3 ile çarpan fonksiyon

print(mydoubler(24))
print(mytripler(24))

students = [
    {"name": "Alice", "grade": 85},
    {"name": "Bob", "grade": 92},
    {"name": "Charlie", "grade": 78},
    {"name": "David", "grade": 95},
]

# Öğrencileri notlarına göre sıralama
students.sort(key=lambda student: student["grade"])

print(students)

"""#Modules

-Modüller programın daha düzenli, yönetilebilir ve genişletilebilir hale getirilmesini sağlar. Modüller, bir araya toplanmış fonksiyonlar, sınıflar ve değişkenlerden oluşur ve belirli bir amaca hizmet eden kod parçalarını gruplamak için kullanılırlar.
"""

import random

num = random.randint(0,50)
hak = 5

# Sayı Tahmin Oyunu

while hak > 0:
  tahmin = int(input("0-50 arasindaki tahmininizi girin:"))

  if tahmin > num:
    hak = hak - 1
    print("Daha küçük sayı giriniz.\nKalan hakkınız: {}".format(hak))

  elif tahmin < num:
    hak = hak - 1
    print("Daha büyük sayı giriniz.\nKalan hakkınız: {}".format(hak))

  else:
    print("Tebrikler sayıyı doğru tahmin ettiniz.\nSayı: {}".format(num))
    break

  if hak == 0:
    print("Hakkınız bitti.\nSayı: {}".format(num))
